#!/bin/bash

stagedfiles=$(git diff -u --diff-filter=d --staged --name-only | grep ".py$") # get names of staged python files, ignoring deleted files
if [ -n "$stagedfiles" ]; then
  # if variable is not empty, run lint and fomatting commands
  # note: empty variable will cause commands to run on all files
  ruff check --fix $stagedfiles             # lint
  ruff check --select I --fix $stagedfiles  # lint imports (not included by default)
  ruff format $stagedfiles                  # format
  git stage $stagedfiles  # stage files after (potential) changes
fi