CREATE TABLE bot_statuses (
 status_id INTEGER PRIMARY KEY AUTOINCREMENT,
 status TEXT NOT NULL
);
INSERT INTO bot_statuses VALUES(1,'Alphonso Davies leave defenders in 2019!');
INSERT INTO bot_statuses VALUES(2,'Jonathan David make goalkeepers cry!');
INSERT INTO bot_statuses VALUES(3,'Tajon Buchanan send fullbacks to retirement!');
INSERT INTO bot_statuses VALUES(4,'the USA wonder why Canada is better now!');
INSERT INTO bot_statuses VALUES(5,'the CONCACAF refs ruin another match!');
INSERT INTO bot_statuses VALUES(6,'Alphonso race a cheetah (and win)!');
INSERT INTO bot_statuses VALUES(7,'Canada send Mexico to their winter coats!');
INSERT INTO bot_statuses VALUES(8,'David outscore every ‘bigger’ nation!');
INSERT INTO bot_statuses VALUES(9,'the USA call Canada ‘just lucky’ again!');
INSERT INTO bot_statuses VALUES(10,'Borjan’s sweatpants win another game!');
INSERT INTO bot_statuses VALUES(11,'Buchanan break ankles for fun!');
INSERT INTO bot_statuses VALUES(12,'Davies make defenders question their life choices!');
INSERT INTO bot_statuses VALUES(13,'Canada teach CONCACAF about real football!');
INSERT INTO bot_statuses VALUES(14,'Costa Rica wonder when Canada got good!');
INSERT INTO bot_statuses VALUES(15,'Davies turn a game into a track meet!');
INSERT INTO bot_statuses VALUES(16,'Borjan stop shots like it’s his day job!');
INSERT INTO bot_statuses VALUES(17,'the USA fans cope in real time!');
INSERT INTO bot_statuses VALUES(18,'Canada silence the Azteca crowd!');
INSERT INTO bot_statuses VALUES(19,'Mexico blame the altitude instead!');
INSERT INTO bot_statuses VALUES(20,'Canadian players dominate in Europe!');
INSERT INTO bot_statuses VALUES(21,'the USA claim dual-nationals as their own!');
INSERT INTO bot_statuses VALUES(22,'David casually outscore CONCACAF legends!');
INSERT INTO bot_statuses VALUES(23,'Canada own the ‘Kings of CONCACAF’ title!');
INSERT INTO bot_statuses VALUES(24,'USA fans google ‘Canada’s soccer history’!');
INSERT INTO bot_statuses VALUES(25,'Panama ask if it’s too late to switch regions!');
INSERT INTO bot_statuses VALUES(26,'Canada break FIFA rankings again!');
INSERT INTO bot_statuses VALUES(27,'Davies make defenders look like training cones!');
INSERT INTO bot_statuses VALUES(28,'Borjan win games in sweatpants!');
INSERT INTO bot_statuses VALUES(29,'the USA call it ‘a fluke’ for the 5th time!');
INSERT INTO bot_statuses VALUES(30,'Buchanan do stepovers for fun!');
INSERT INTO bot_statuses VALUES(31,'David ghost past defenses like a ninja!');
INSERT INTO bot_statuses VALUES(32,'Mexico wonder what happened in 2021!');
INSERT INTO bot_statuses VALUES(33,'Alphonso outrun Wi-Fi signals!');
INSERT INTO bot_statuses VALUES(34,'USA fans realize Canada has real talent!');
INSERT INTO bot_statuses VALUES(35,'Larin celebrate with a casual shrug!');
INSERT INTO bot_statuses VALUES(36,'Canada become the true giants of CONCACAF!');
INSERT INTO bot_statuses VALUES(37,'Canada qualify while others struggle!');
INSERT INTO bot_statuses VALUES(38,'Davies make 99 pace look slow!');
INSERT INTO bot_statuses VALUES(39,'Borjan collect another clean sheet!');
INSERT INTO bot_statuses VALUES(40,'the USA wonder why their golden generation isn’t winning!');
INSERT INTO bot_statuses VALUES(41,'Canada turn ‘underdog’ into ‘top dog’!');
INSERT INTO bot_statuses VALUES(42,'David steal another Golden Boot race!');
INSERT INTO bot_statuses VALUES(43,'Canada’s midfield run laps around the opposition!');
INSERT INTO bot_statuses VALUES(44,'Davies delete fullbacks from existence!');
INSERT INTO bot_statuses VALUES(45,'CONCACAF defenders have nightmares about Canada!');
INSERT INTO bot_statuses VALUES(46,'the USA wish they had Alphonso Davies!');
INSERT INTO bot_statuses VALUES(47,'David and Buchanan make defenders retire!');
INSERT INTO bot_statuses VALUES(48,'Canada dunk on ‘bigger’ nations!');
INSERT INTO bot_statuses VALUES(49,'the world finally respect Canadian soccer!');
INSERT INTO bot_statuses VALUES(50,'Borjan’s sweatpants become legendary!');
INSERT INTO bot_statuses VALUES(51,'Jesse Marsch turn Canada into a pressing machine!');
INSERT INTO bot_statuses VALUES(52,'Eustáquio make midfield look easy!');
INSERT INTO bot_statuses VALUES(53,'Larin casually score on every CONCACAF keeper!');
INSERT INTO bot_statuses VALUES(54,'Johnston slide tackle his way through history!');
INSERT INTO bot_statuses VALUES(55,'Jesse Marsch outcoach his former employers!');
INSERT INTO bot_statuses VALUES(56,'Eustáquio ping 40-yard passes for fun!');
INSERT INTO bot_statuses VALUES(57,'Larin become Canada''s all-time top scorer!');
INSERT INTO bot_statuses VALUES(58,'Johnston defend like his life depends on it!');
INSERT INTO bot_statuses VALUES(59,'Jesse Marsch yell in three languages at once!');
INSERT INTO bot_statuses VALUES(60,'Eustáquio be the midfield general we needed!');
INSERT INTO bot_statuses VALUES(61,'Larin ghost into the box (again)!');
INSERT INTO bot_statuses VALUES(62,'Johnston leave wingers in his back pocket!');
INSERT INTO bot_statuses VALUES(63,'Eustáquio run the midfield like a CEO!');
INSERT INTO bot_statuses VALUES(64,'Larin score while looking half-asleep!');
INSERT INTO bot_statuses VALUES(65,'Johnston prove fullbacks can be cool!');

